name: Build agents image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'agents/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'agents/**'

env:
  IMAGE_NAME: klimdos/moto-news-agents

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate semantic version from Git
      id: version
      run: |
        set -e
        ARTEFACT_VERSION=$(git describe --long --always --tags | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")
        echo "ARTEFACT_VERSION=${ARTEFACT_VERSION}" >> $GITHUB_ENV
        echo "version=${ARTEFACT_VERSION}" >> $GITHUB_OUTPUT

    - name: Print ARTEFACT_VERSION
      run: echo "ARTEFACT_VERSION is ${{ env.ARTEFACT_VERSION }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image with caching
      uses: docker/build-push-action@v6
      with:
        context: ./agents
        file: ./agents/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.ARTEFACT_VERSION }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

    - name: Cleanup Docker environment
      run: docker builder prune --force
